### PR TITLE
Constant fold casts of serializble enums

### LINKED ISSUE #3178: Error operating bit<X> var casted from enum
Hi,
We hit error when operating bit\<X\> variable casted from enum type.
```
enum bit<1> TableType {TT_ACL = 0, TT_FWD = 1};

const bit<10> b10 = (bit<10>)(bit<1>)TableType.TT_ACL;
const bit<10> mask = 1 << 9;

const bit<10> test1 = b10 << 3;
const bit<10> test2 = mask | b10;
```

Here is the detailed p4c compiler output.
```
bug/test_enum.p4(5): [--Werror=expected] error: cast: expected an integer value
const bit<10> b10 = (bit<10>)(bit<1>)TableType.TT_ACL;
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bug/test_enum.p4(8): [--Werror=invalid] error: <<: Cannot evaluate initializer for constant
const bit<10> test1 = b10 << 3;
                      ^^^^^^^^
bug/test_enum.p4(9): [--Werror=invalid] error: |: Cannot evaluate initializer for constant
const bit<10> test2 = mask | b10;
                      ^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

Fixes #3178

### CODE REVIEW

File: frontends/p4/commonInlining.h [hunk 1]
```diff
@@ -169,8 +169,9 @@ class InlineDriver : public Visitor {
  public:
     InlineDriver(
         InlineList* toInline, AbstractInliner<InlineList, InlineWorkList> *inliner) :
-            toInline(toInline), inliner(inliner)
-    { CHECK_NULL(toInline); CHECK_NULL(inliner); setName("InlineDriver"); }
+            toInline(toInline), inliner(inliner) {
+        CHECK_NULL(toInline); CHECK_NULL(inliner);
+        setName((cstring("InlineDriver_") + cstring(inliner->name())).c_str()); }
```
Comment (mbudiu-vmw) [inline frontends/p4/commonInlining.h:174]: This is an unrelated improvement which will cause the various inlining passes to have different names.

**Review by rst0git — APPROVED** [review]
LGTM
