### PR TITLE
Missing null pointer check

### LINKED ISSUE #2681: Compiler Bug compiling test program tuple4.p4
I was creating a new Ubuntu 20.04 Linux VM this weekend with most recent version of open source P4 dev tools compiled from source code and experienced a compiler bug when attempting to compile one of the newer test program tuple4.p4:
```
$ p4test --version
p4test
Version 1.2.0 (SHA: 01b63cb3d BUILD: RELEASE)

$ cd testdata/p4_16_samples
$ p4test tuple4.p4
In file: /home/vagrant/p4c/lib/crash.cpp:256
Compiler Bug: Exiting with SIGSEGV
```
I did not use any options to `cmake` or `make` when building -- just whatever the defaults there are.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #2681

### CODE REVIEW

File: frontends/common/constantFolding.cpp [hunk 1]
```diff
@@ -220,10 +220,12 @@ const IR::Node* DoConstantFolding::preorder(IR::ArrayIndex* e) {
                 return e;
             }
             auto value = getConstant(e->left);
+            if (!value)
```
Comment (fruffy) [inline frontends/common/constantFolding.cpp:223]: What causes this expression to be null in the first place?

**Review by fruffy — APPROVED** [review]

File: frontends/common/constantFolding.cpp (hunk 1 above)
Comment (mbudiu-vmw) [reply frontends/common/constantFolding.cpp:223]: This returns null if the expression is not a constant.
For an array it will return a non-null constant only if the array is a list expression.
When we add array initializers we'll be able to have constant arrays too (I am not sure that having constant headers is useful, though, but it should work).
