### PR TITLE
Dpdk backend: Use vector to populate checksum struct

### LINKED ISSUE #3665: dkdp backend generates non-deterministic output
Some dpdk tests fail intermittently because the .spec output file produced is non-deterministic.
On my machine for example `./dpdk/testdata/p4_16_samples/psa-example-parser-checksum.p4.test` generates the following output:
```
Checking psa-example-parser-checksum.p4.spec
Comparing /home/mbudiu/git/p4c/testdata/p4_16_samples_outputs/psa-example-parser-checksum.p4.spec and ./tmpakzkcq25/psa-example-parser-checksum.p4.spec
diff -B -u -w /home/mbudiu/git/p4c/testdata/p4_16_samples_outputs/psa-example-parser-checksum.p4.spec ./tmpakzkcq25/psa-example-parser-checksum.p4.spec >&2
--- /home/mbudiu/git/p4c/testdata/p4_16_samples_outputs/psa-example-parser-checksum.p4.spec	2022-11-04 13:09:13.776197386 -0700
+++ ./tmpakzkcq25/psa-example-parser-checksum.p4.spec	2022-11-04 13:10:42.752111042 -0700
@@ -32,8 +32,8 @@
 }
 
 struct cksum_state_t {
-	bit<16> state_1
 	bit<16> state_0
+	bit<16> state_1
 }
```

This usually happens when iterating over a non-deterministic collection, such as set.

### PR DESCRIPTION
**Pull request by usha1830**
Fixes #3665

### CODE REVIEW

File: backends/dpdk/dpdkArch.h [hunk 1]
```diff
@@ -600,25 +602,27 @@ class CollectInternetChecksumInstance : public Inspector {
 // side(a question related to endianness)
 class InjectInternetChecksumIntermediateValue : public Transform {
     DpdkProgramStructure *structure;
+    std::vector<cstring> *csum_vec;
 
  public:
-    explicit InjectInternetChecksumIntermediateValue(DpdkProgramStructure *structure) :
-        structure(structure) {}
+    explicit InjectInternetChecksumIntermediateValue(DpdkProgramStructure *structure,
```
Comment (mbudiu-vmw) [inline backends/dpdk/dpdkArch.h:608]: with two arguments "explicit" is no longer necessary

**Review by mbudiu-vmw — APPROVED** [review]
