### PR TITLE
Correctly attach the dontmerge annotation in the desugar_varbit_extract pass.

### LINKED ISSUE #5138: Tofino backend: compiler bug when extracting varbit header
Versions: 
   * open-p4studio: 0f2ad6
   * p4c: 660779
  
Compiling the attached P4 program (as GZIP since GitHub does not allow a `.p4` extension) with open-p4studio produces the following error
```
debian@open-p4studio:~/open-p4studio/foo$ make
[  0%] Built target bf-p4c
[  0%] Built target driver
[100%] Generating bug/tofino/bf-rt.json
running find /home/debian/open-p4studio/foo/bug/tofino \( -name pipe* -or -name graphs -or -name logs -or -name visualization \) -type d -exec rm -rf {} +
running find /home/debian/open-p4studio/foo/bug/tofino \( -path *.json -or -path *.conf -or -path *.p4pp -or -path *.bfa -or -path *.log -or -path *.bin -or -path *.txt \) -type f -exec rm -f {} +
running cc -E -x assembler-with-cpp -D__TARGET_TOFINO__=1 -D__p4c__=1 -D__p4c_major__=9 -D__p4c_minor__=13               -D__p4c_patchlevel__=4 -D__p4c_version__=\"9.13.4\" -C -undef -nostdinc -x assembler-with-cpp -I /home/debian/open-p4studio/install/share/p4c/p4include -o /home/debian/open-p4studio/foo/bug/tofino/bug.p4pp /home/debian/open-p4studio/bug.p4
running /home/debian/open-p4studio/install/bin/p4c-barefoot --nocpp -D__TARGET_TOFINO__=1 -D__p4c__=1 -D__p4c_major__=9 -D__p4c_minor__=13               -D__p4c_patchlevel__=4 -D__p4c_version__=\"9.13.4\" -g -I /home/debian/open-p4studio/install/share/p4c/p4include --p4v=16 --target tofino --arch tna -o /home/debian/open-p4studio/foo/bug/tofino /home/debian/open-p4studio/foo/bug/tofino/bug.p4pp --create-graphs --verbose -Ttable_placement:3,table_summary:1,table_dependency_graph:3,table_dependency_summary:3,allocate_phv:1,allocator_base:3,trivial_allocator:5,greedy_allocator:5,alias:1,,allocate_clot:1,clot_info:1,split_parser_state:1,allocate_parser_match_register:1,allocate_parser_checksum:1,lower_parser:1,decaf*:1,characterize_parser.h:1,bridged_packing:1,ixbar_info:3 -Tstage_advance:3>/home/debian/open-p4studio/foo/bug/tofino/stage_adv.log --bf-rt-schema bug/tofino/bf-rt.json

1 error, 0 warnings generated.

In file: /home/debian/open-p4studio/pkgsrc/p4-compilers/p4c/ir/ir-inline.h:90
Compiler Bug: /home/debian/open-p4studio/pkgsrc/p4-compilers/p4c/ir/ir-inline.h:90: Null n

Internal compiler error. Please submit a bug report with your code.
make[2]: *** [CMakeFiles/bug-tofino.dir/build.make:80: bug/tofino/bf-rt.json] Error 4
make[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/bug-tofino.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
The error only occurs when extracting a `varbit` header field.

The build was prepared with
```
debian@open-p4studio:~/open-p4studio/foo$ cmake ../p4studio/ -DCMAKE_INSTALL_PREFIX=$SDE_INSTALL -DCMAKE_MODULE_PATH=$SDE/cmake -DP4FLAGS="-v" -DP4_NAME=bug -DP4_PATH=/home/debian/open-p4studio/bug.p4
--
Using SDE: /home/debian/open-p4studio
--
Using SDE_INSTALL: /home/debian/open-p4studio/install
-- Python3 found: /usr/bin/python3.9
-- Python3 version: 3.9.2
-- Python3 include dir: /usr/include/python3.9
-- Python3 libraries: /usr/lib/x86_64-linux-gnu/libpython3.9.so
--
P4_LANG: p4-16
P4C: /home/debian/open-p4studio/install/bin/bf-p4c
P4C-GEN_BRFT-CONF: /home/debian/open-p4studio/install/bin/p4c-gen-bfrt-conf
P4C-MANIFEST-CONFIG: /home/debian/open-p4studio/install/bin/p4c-manifest-config
--
P4_PATH: /home/debian/open-p4studio/bug.p4
P4_NAME: bug
--
P4FLAGS: -v
-- Configuring done
-- Generating done
-- Build files have been written to: /home/debian/open-p4studio/foo
```

[bug.p4.gz](https://github.com/user-attachments/files/18907328/bug.p4.gz)

### PR DESCRIPTION
**Pull request by fruffy**
Looks like the annotation was not constructed correctly. Also unsure whether this annotation ever worked in the first place. This attempt tries to fix it. Since we do not know the direction at this point I added an annotation for both directions.

Fixes #5138.

I added the test program to the Tofino tests. Might be worthwhile to add all the tests to a dedicated Tofino directory instead and run the compiler with reference files.

### CODE REVIEW

**Comment by ChrisDodd** [comment]
I'm not at all familiar with this code -- it seems odd to me that that `@dontmerge` requires the gress as an argument -- it seems like a pointless extra check.  The only reason I could think of is for a parser called in both ingress and egress, and you only want to prevent merging in one and not the other.

Having two annotations won't work, as the code that checks this annotation just calls `getAnnotation` so will only see the first one.  From backends/tofino/bf-p4c/parde/extract_parser.cpp:

~~~
        if (auto dontmerge = state->getAnnotation("dontmerge"_cs)) {
            if (dontmerge->getExpr().size()) {
                auto gress = dontmerge->getExpr(0)->to<IR::StringLiteral>();
                if (gress->value == toString(parser->thread)) { 
                    backendState->dontMerge = true;
                }
            }
        }
~~~

It might make more sense to add `else backendState->dontMerge = true` on 2nd if here (so it will catch a bare `@dontmerge` with no gress.  That way `@dontmerge` will affect all threads, while `@dontmerge("ingress")` would affect just ingress.

File: backends/tofino/bf-p4c/midend/desugar_varbit_extract.h [hunk 1]
```diff
@@ -123,7 +123,7 @@ class AnnotateVarbitExtractStates : public Transform {
             if (!method) continue;
 
             if (method->member == "extract" && call->arguments->size() == 2) {
-                state->addOrReplaceAnnotation("dontmerge"_cs, {});
+                state->addOrReplaceAnnotation(new IR::Annotation("dontmerge"_cs, {}));
```
Comment (ChrisDodd) [inline backends/tofino/bf-p4c/midend/desugar_varbit_extract.h:126]: This seems like a pointless change

**Review by ChrisDodd — APPROVED** [review]

File: backends/tofino/bf-p4c/midend/desugar_varbit_extract.h (hunk 1 above)
Comment (fruffy) [reply backends/tofino/bf-p4c/midend/desugar_varbit_extract.h:126]: Without this change, a later visitor traversal will cause a compiler bug. There might be something wrong with the construction of the annotation here.

Comment (fruffy) [reply backends/tofino/bf-p4c/midend/desugar_varbit_extract.h:126]: The problem is that {} is not a good `const IR::Expression*` argument. Not sure why this compiles, maybe decays to a null pointer?

Comment (ChrisDodd) [reply backends/tofino/bf-p4c/midend/desugar_varbit_extract.h:126]: Looks like we're missing the overload of `addOrReplaceAnnotation` that takes a `std::initializer_list`.  It is weird that it doesn't give an error -- `{}` should not be a valid pointer.

Comment (fruffy) [reply backends/tofino/bf-p4c/midend/desugar_varbit_extract.h:126]: It looks like the Annotation interface is a little dirty, ideally we should find these issues at compile time. 

I could try to delete the overloaded nullpointer signature or see whether I can enforce references instead.
