### PR TITLE
Type check that RHS of shift is integral type

### LINKED ISSUE #5094: Shift by a string literal is not rejected by type checker
I modified https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/arith5-bmv2.p4:

```p4
    action shift()
    { h.h.c = (int<64>)(h.h.a >> "aaaa"); sm.egress_spec = 0; }
```

Note that this code does not make any sense and should be rejected by the type checker. Howerver, it is not rejected:

```bash
$ ./build/p4c/p4test p4c/testdata/p4_16_samples/arith5-bmv2.p4
# [nothing, exitcode = 0]
```

If the shift is replaced with addition, the check works:

```
p4c/testdata/p4_16_samples/arith5-bmv2.p4(30): [--Werror=type-error] error: +: cannot be applied to expression '"aaaa"' with type 'string'
    { h.h.c = (int<64>)(h.h.a + "aaaa"); sm.egress_spec = 0; }
                                     ^
```

### PR DESCRIPTION
**Pull request by dmatousek**
Replaces #5099.

Fixes #5094 and #5100. There was no check that RHS of shift is an integral type. In most targets, this was probably a backend error prior, but theoretically this could be a breaking change.

### CODE REVIEW

File: frontends/p4/typeChecking/typeCheckExpr.cpp [hunk 1]
```diff
@@ -915,6 +915,12 @@ const IR::Node *TypeInferenceBase::shift(const IR::Operation_Binary *expression)
         // getTypeType should have already taken care of the error message
         return expression;
     }
+    // FIXME: #5100, strip the new-type introduced by `type` keyword for now. According to the spec,
+    // such code should be rejected, but before #5099 it was accepted, so keep it accepted for now,
+    // until we discuss what is the right approach here.
+    if (const auto *rt = rtype->to<IR::Type_Newtype>()) {
+        rtype = getTypeType(rt->type);
```
Comment (ChrisDodd) [inline frontends/p4/typeChecking/typeCheckExpr.cpp]: IMO we should probably reject this (and fix the testcase in question by adding an explicit cast), since the spec does call out that the cast is required.  Thta *might* break some existing code, but the fix for that code is simple (add the cast)

I'm ok with checking this in and doing that later.

Comment (dmatousek) [reply frontends/p4/typeChecking/typeCheckExpr.cpp]: Included in this PR.
