### PR TITLE
Prepend rather than append variable declarations; fixes #1989

### LINKED ISSUE #1989: Compiler bug with action assignment
The following action causes a compiler bug:

```P4
  action assign_non_const_array_index() {
    hdr.ethernet_stack[1] = hdr.ethernet_stack[meta.color];
  }
```

I'm not a P4 expert, so using enums as array index as well be illegal P4 code, but then the compiler should generate an error instead of crashing.

Complete P4 program:

```P4
#include <core.p4>
#include <v1model.p4>

enum meter_color_t { COLOR_GREEN, COLOR_RED, COLOR_YELLOW }

struct test_metadata_t {
  bit<32> color;
  meter_color_t enum_color;
  bit<32> other_metadata;
  bit<16> smaller_metadata;
}

header ethernet_t {
  bit<48> dstAddr;
  bit<48> srcAddr;
  bit<16> etherType;
}

struct headers {
  ethernet_t ethernet;
  ethernet_t ethernet2;
  ethernet_t[2] ethernet_stack;
}

parser parser_stub(packet_in packet, out headers hdr,
                   inout test_metadata_t meta,
                   inout standard_metadata_t standard_metadata) {
  state start {
    transition accept;
  }
}

control egress_stub(inout headers hdr, inout test_metadata_t meta,
                    inout standard_metadata_t standard_metadata) {
  apply {}
}

control ingress_stub(inout headers hdr, inout test_metadata_t meta,
                     inout standard_metadata_t standard_metadata) {
  apply {}
}

control deparser_stub(packet_out packet, in headers hdr) {
  apply {}
}

control verify_checksum_stub(inout headers hdr, inout test_metadata_t meta) {
  apply {}
}

control compute_checksum_stub(inout headers hdr, inout test_metadata_t meta) {
  apply {}
}

control ingress(inout headers hdr, inout test_metadata_t meta,
                inout standard_metadata_t standard_metadata) {
  action assign_non_const_array_index() {
    hdr.ethernet_stack[1] = hdr.ethernet_stack[meta.color];
  }
  table acl_table {
    actions = {
      assign_non_const_array_index;
    }
    key = {
      hdr.ethernet.etherType: exact;
    }
  }
  apply {
    acl_table.apply();
  }
}

V1Switch(parser_stub(), verify_checksum_stub(), ingress(), egress_stub(),
         compute_checksum_stub(), deparser_stub()) main;

```

Compiler invocation:
```bash
p4c-bm2-ss --arch v1model action_assignments_crash.p4
In file: /tmp/p4c/frontends/p4/typeChecking/typeChecker.cpp:168
Compiler Bug: Could not find type of ethernet_t tmp
```

More detailed output:

```
Resolved ingress to control ingress(inout headers hdr, inout test_metadata_t meta, inout standard_metadata_t standard_metadata)() {
  action NoAction_0/NoAction() { }
  action assign_non_const_array_index() {
    tmp = hdr.ethernet_stack[meta.color];
    hdr.ethernet_stack[1] = tmp; }
  table acl_table_0/acl_table @name("ingress.acl_table") {
    actions = { assign_non_const_array_index();
      @defaultonly NoAction_0/NoAction(); }
    key = { @name("hdr.ethernet.etherType") hdr.ethernet.etherType: exact; }
    default_action = NoAction_0/NoAction(); }
  ethernet_t tmp
  acl_table_0/acl_table.apply(); }
Resolved egress_stub to control egress_stub(inout headers hdr, inout test_metadata_t meta, inout standard_metadata_t standard_metadata)() { }
Resolved compute_checksum_stub to control compute_checksum_stub(inout headers hdr, inout test_metadata_t meta)() { }
Resolved deparser_stub to control deparser_stub(packet_out packet, in headers hdr)() { }
      ResolveReferences 2903.5 usec
    P4::TypeChecking invoking P4::TypeInference
Looking up tmp found ethernet_t tmp
Left value <PathExpression>(82392) tmp
Left value <PathExpression>(82166) tmp
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: external/com_github_p4lang_p4c/frontends/p4/typeChecking/typeChecker.cpp:168
Compiler Bug: Could not find type of ethernet_t tmp
```

Compiler version:
```bash
# p4c-bm2-ss --version
p4c-bm2-ss
Version 1.1.0-rc1 (SHA: 3621f973)
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

File: midend/copyStructures.cpp [hunk 1]
```diff
@@ -49,7 +49,11 @@ const IR::Node* RemoveAliases::postorder(IR::P4Parser* parser) {
 
 const IR::Node* RemoveAliases::postorder(IR::P4Control* control) {
     if (!declarations.empty()) {
-        control->controlLocals.append(declarations);
+        // prepend declarations: they must come before any actions
+        // that may have been modified
+        auto vec = new IR::IndexedVector<IR::Declaration>(declarations);
+        vec->append(control->controlLocals);
+        control->controlLocals = *vec;
```
Comment (ChrisDodd) [inline midend/copyStructures.cpp]: Should be able to use

    control->controlLocals.insert(control->controlLocals.begin(), declarations.begin(), declarations.end())

to do the insertion directly at the beginning, or is that not as clear?  Maybe add a `prepend` method to `IndexedVector`?

Comment (mbudiu-vmw) [reply midend/copyStructures.cpp]: I have added a prepend method to our Vector classes.
