### PR TITLE
Fix def-use analysis bug when handling virtual methods

### LINKED ISSUE #3417: Compiler bug in simplifyDefUse
When compiling this code in the following extern inside a parser, the compiler throws a bug saying that it reached an unreachable expression in FindUninitialized.
```c
    Register<bit<128>, bit<16>>(32w0, 128w0) reg;
    
    RegisterAction<bit<128>, bit<16>, bit<64>>(reg) regAct = {
        void apply(inout bit<128> val, out bit<64> rv) {
            return;
        }
    };
```
Full error:  (with -vvvv)
```
SimplifyDefUse_0_Cloner
P4::TypeChecking_0_ResolveReferences
P4::TypeChecking_1_TypeInference
PassRepeated_0_TypeChecking
/mnt/find_uninit_v1model.p4(41): [--Wwarn=uninitialized_out_param] warning: out parameter 'rv' may be uninitialized when 'apply' terminates
        void apply(inout bit<128> val, out bit<64> rv) {
                                                   ^^
/mnt/bf-p4c-tools/find_uninit_v1model.p4(41)
        void apply(inout bit<128> val, out bit<64> rv) {
             ^^^^^
In file: /mnt/compilers/p4c/frontends/p4/simplifyDefUse.cpp:402
Compiler Bug: reached an unreachable expression in FindUninitialized

```
I have attached the corresponding p4 below.
[find_uninit_v1model.p4.txt](https://github.com/p4lang/p4c/files/9021371/find_uninit_v1model.p4.txt)

---
These were the last few passes:

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>
Fixes #3417

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
The fix is just 1 line, but I added a few helper methods as well.

File: frontends/p4/simplifyDefUse.cpp [hunk 1]
```diff
@@ -572,6 +580,7 @@ class FindUninitialized : public Inspector {
         headerDefs->clear();
         initHeaderParams(parser->getApplyMethodType()->parameters);
         visitVirtualMethods(parser->parserLocals);
+        unreachable = false;
```
Comment (mbudiu-vmw) [inline frontends/p4/simplifyDefUse.cpp:583]: this is the fix; this code is similar to the handling of controls.
If there are virtual methods they may leave "unreachable" on true.

File: frontends/p4/ternaryBool.h [hunk 2]
```diff
@@ -17,15 +17,17 @@ limitations under the License.
 #ifndef _FRONTENDS_P4_TERNARYBOOL_H_
 #define _FRONTENDS_P4_TERNARYBOOL_H_
 
+#include "lib/cstring.h"
+
 namespace P4 {
+enum class TernaryBool {
```
Comment (fruffy) [inline frontends/p4/ternaryBool.h:23]: Might be missing a newline here?

**Review by fruffy — APPROVED** [review]
