### PR TITLE
Try to make exename portable. Refactor searchForIncludePath.

### LINKED ISSUE #3812: exename does not work on Mac OS X
When I was reading the code for exename, I see it does not have a fallback for searching the PATH env if the argv0 was not a path.
csh shell does not set `_` env variable either.
There might be other shells which don't set `_` env variable either either.

### PR DESCRIPTION
**Pull request by fruffy**
Fixes #3812.

Ran into this while working on a PR. Turns out exename doesn't seem to properly work. Maybe this approach works better? Still trying to figure out the right approach for `getExecutablePath`.

Also use `std::filesystem::path` to set the include path instead of char manipulation. 

This change preserves all APIs, still marking as breaking in case there are some differences in behavior.

### CODE REVIEW

File: lib/exename.cpp [hunk 1]
```diff
@@ -16,58 +16,77 @@ limitations under the License.
...
-    if ((len = readlink("/proc/self/exe", buffer, sizeof(buffer) - 1)) > 0 ||
-        (len = readlink("/proc/curproc/exe", buffer, sizeof(buffer) - 1)) > 0 ||
-        (len = readlink("/proc/curproc/file", buffer, sizeof(buffer) - 1)) > 0 ||
-        (len = readlink("/proc/self/path/a.out", buffer, sizeof(buffer) - 1)) > 0) {
-        buffer[len] = 0;
-    } else if (argv0 && argv0[0] == '/') {
-        snprintf(buffer, sizeof(buffer), "%s", argv0);
-    } else if (argv0 && strchr(argv0, '/')) {
-        convertToAbsPath(argv0, buffer);
-    } else if (getenv("_")) {
```
Comment (fruffy) [inline lib/exename.cpp:64]: Not sure about this use case. Does it work on MacOS? When is this needed?

File: lib/exename.cpp [hunk 2]
```diff
@@ -16,58 +16,75 @@ limitations under the License.
...
+std::filesystem::path getExecutablePath(const std::filesystem::path &suggestedPath) {
+#if defined(__linux__) || defined(__FreeBSD__) || defined(__NetBSD__)
+    // Find the path of the executable.  We use a number of techniques that may fail or work on
+    // different systems, and take the first working one we find.  Fallback to not overriding the
+    // compiled-in installation path.
+    std::array<std::string, 4> paths = {
+        "/proc/self/exe",         // Linux
+        "/proc/curproc/file",     // FreeBSD
+        "/proc/curproc/exe",      // NetBSD
+        "/proc/self/path/a.out",  // others?
```
Comment (ChrisDodd) [inline lib/exename.cpp:45]: Solaris (I think)

File: lib/exename.cpp (hunk 1 above)
Comment (ChrisDodd) [reply lib/exename.cpp:64]: This should work if the compiler was invoked by bash, regardless of system.  Bash (and possibly other shells) set this envvar to the full, absolute path of the program being invoked when they call exec.  It is a useful fallback if argv0 is null or just a command name (that was looked up in $PATH).

File: lib/exename.cpp [hunk 3]
```diff
@@ -16,58 +16,75 @@ limitations under the License.
...
+    static std::array<char, PATH_MAX> buffer{};
+    // TODO: Do we need to support this?
+    DWORD size = GetModuleFileNameA(nullptr, buffer.data(), static_cast<DWORD>(buffer.size()));
+    if (size > 0 && size < buffer.size()) {
+        return (buffer.data());
+    }
+#endif
+    // If the above fails, try to convert argv0 to a path.
+    if (std::filesystem::exists(suggestedPath)) {
+        return suggestedPath;
```
Comment (ChrisDodd) [inline lib/exename.cpp:74]: What happens here if `suggestedPath` is a relative path?  Previously we would prepend `$CWD` to make an absolute path.

**Review by ChrisDodd — APPROVED** [review]

File: backends/dpdk/options.cpp [hunk 4]
```diff
@@ -8,11 +8,18 @@ namespace P4::DPDK {
 using namespace P4::literals;
 
 std::vector<const char *> *DpdkOptions::process(int argc, char *const argv[]) {
+    auto executablePath = getExecutablePath(argv[0]);
+    if (executablePath.empty()) {
+        std::cerr << "Could not determine executable path" << std::endl;
+        return nullptr;
+    }
+    exe_name = cstring(executablePath.stem().c_str());
```
Comment (asl) [inline backends/dpdk/options.cpp:16]: Seems to be unused, no?

File: backends/bmv2/portable_common/options.cpp [hunk 5]
```diff
@@ -8,9 +8,15 @@ namespace P4::BMV2 {
 using namespace P4::literals;
 
 std::vector<const char *> *PortableOptions::process(int argc, char *const argv[]) {
+    auto executablePath = getExecutablePath(argv[0]);
+    if (executablePath.empty()) {
+        std::cerr << "Could not determine executable path" << std::endl;
+        return nullptr;
+    }
+    exe_name = cstring(executablePath.stem().c_str());
```
Comment (asl) [inline backends/bmv2/portable_common/options.cpp:16]: Unused?

File: backends/tofino/bf-p4c/bf-p4c-options.cpp [hunk 6]
```diff
@@ -712,14 +713,21 @@ std::vector<const char *> *BFN_Options::process(int argc, char *const argv[]) {
     // Don't know, and I'm at the end of my patience with it ...
     if (!processed) outputDir = "."_cs;
 
+    auto executablePath = getExecutablePath(argv[0]);
+    if (executablePath.empty()) {
+        std::cerr << "Could not determine executable path" << std::endl;
+        return nullptr;
+    }
+    exe_name = cstring(executablePath.stem().c_str());
```
Comment (asl) [inline backends/tofino/bf-p4c/bf-p4c-options.cpp:721]: ditto

File: frontends/common/parser_options.cpp [hunk 7]
```diff
@@ -355,53 +357,35 @@ void ParserOptions::setInputFile() {
...
-        includePathOut = strdup(possiblePath);
-    return true;
-}
-
-}  // namespace
-
 bool ParserOptions::searchForIncludePath(const char *&includePathOut,
-                                         std::vector<cstring> userSpecifiedPaths,
+                                         const std::vector<cstring> &userSpecifiedPaths,
                                          const char *exename) {
```
Comment (asl) [inline frontends/common/parser_options.cpp:362]: Can `exename` be converted to `std::filesystem::path` while here?

File: frontends/common/parser_options.cpp [hunk 8]
```diff
@@ -355,53 +357,35 @@ void ParserOptions::setInputFile() {
...
-    else
-        includePathOut = strdup(possiblePath);
-    return true;
-}
-
-}  // namespace
-
 bool ParserOptions::searchForIncludePath(const char *&includePathOut,
-                                         std::vector<cstring> userSpecifiedPaths,
+                                         const std::vector<cstring> &userSpecifiedPaths,
```
Comment (asl) [inline frontends/common/parser_options.cpp:361]: Change to vector of `std::filesystem::path`?

File: frontends/common/parser_options.cpp [hunk 9]
```diff
@@ -355,53 +357,35 @@ void ParserOptions::setInputFile() {
...
 
 std::vector<const char *> *ParserOptions::process(int argc, char *const argv[]) {
-    searchForIncludePath(p4includePath, {"p4include"_cs, "../p4include"_cs, "../../p4include"_cs},
-                         exename(argv[0]));
+    auto executablePath = getExecutablePath(argv[0]);
+    if (executablePath.empty()) {
+        std::cerr << "Could not determine executable path" << std::endl;
+        return nullptr;
+    }
+    exe_name = cstring(executablePath.stem().c_str());
```
Comment (asl) [inline frontends/common/parser_options.cpp:380]: Unused

File: lib/alloc_trace.cpp [hunk 10]
```diff
@@ -75,7 +75,8 @@ std::ostream &operator<<(std::ostream &out, const AllocTrace &at) {
     std::sort(sorted.begin(), sorted.end(), [](auto &a, auto &b) { return a.first > b.first; });
 #if HAVE_LIBBACKTRACE
     if (!global_backtrace_state)
-        global_backtrace_state = backtrace_create_state(exename(), 1, bt_error, &out);
+        global_backtrace_state =
+            backtrace_create_state(getExecutablePath().c_str(), 1, bt_error, &out);
```
Comment (asl) [inline lib/alloc_trace.cpp:79]: Per documentation:
>  Create state information for the backtrace routines.  This must be
called before any of the other routines, and its return value must
be passed to all of the other routines.  FILENAME is the path name
of the executable file; if it is NULL the library will try
system-specific path names.  If not NULL, FILENAME must point to a
permanent buffer.

So, we'd need to ensure `getExecutablePath` output is permanent. Probably the easiest (though a bit dirty) way is to roundtrip via `cstring` here...

File: lib/exename.cpp [hunk 11]
```diff
@@ -16,58 +16,83 @@ limitations under the License.
...
+            return std::filesystem::canonical(path);
+        } catch (const std::filesystem::filesystem_error &) {
+            // Ignore and try the next path.
+        }
+    }
+#elif defined(__APPLE__)
+    std::array<char, PATH_MAX> buffer{};
+    uint32_t size = static_cast<uint32_t>(buffer.size());
+    if (_NSGetExecutablePath(buffer.data(), &size) == 0) {
+        // TODO: What to do about the allocation here?
```
Comment (asl) [inline lib/exename.cpp:61]: What is the problem here?

File: lib/exename.cpp [hunk 12]
```diff
@@ -16,58 +16,83 @@ limitations under the License.
...
+#endif
 
-    char cwd[PATH_MAX];
-    if (!getcwd(cwd, sizeof(cwd))) return;
-    const size_t cwdLen = strlen(cwd);
-    if (cwdLen == 0) return;
-    const char *separator = cwd[cwdLen - 1] == '/' ? "" : "/";
+std::filesystem::path getExecutablePath(const std::filesystem::path &suggestedPath) {
+#if defined(__linux__) || defined(__FreeBSD__) || defined(__NetBSD__)
+    // Find the path of the executable.  We use a number of techniques that may fail or work on
```
Comment (asl) [inline lib/exename.cpp:38]: Maybe adopt https://github.com/gpakosz/whereami? There is also https://original.boost.org/doc/libs/1_84_0/doc/html/boost/dll/program_location_idm4410.html

**Review by asl — COMMENTED** [review]
See comments

File: backends/dpdk/options.cpp (hunk 4 above)
Comment (fruffy) [reply backends/dpdk/options.cpp:16]: This sets the variable here, which is used by other parts in the compiler.

https://github.com/p4lang/p4c/blob/main/frontends/common/parser_options.h#L75

Imho should be set whenever we call `getExecutablePath`

File: frontends/common/parser_options.cpp (hunk 7 above)
Comment (fruffy) [reply frontends/common/parser_options.cpp:362]: This would break downstream use of that function, figured I should do that in a separate PR. Ditto for all the cstring typing of variables that should be a path.

File: lib/exename.cpp (hunk 11 above)
Comment (fruffy) [reply lib/exename.cpp:61]: Outdate, we now return a copy instead of a strdup char pointer.

File: lib/exename.cpp (hunk 12 above)
Comment (fruffy) [reply lib/exename.cpp:38]: Figured we shouldn't depend on external dependencies for a utility like this. Particularly boost which we want to get rid of. Let me take a look at `whereami`

File: backends/dpdk/options.cpp (hunk 4 above)
Comment (asl) [reply backends/dpdk/options.cpp:16]: Ah, ok, very.. unexpected side effect. Can we spell it like `this->exe_name` to outline that this is member variable?

File: lib/exename.cpp (hunk 12 above)
Comment (asl) [reply lib/exename.cpp:38]: Yes. Though there is bunch of domain knowledge here :(

**Comment by fruffy** [comment]
The Ubuntu failure is unrelated, should be fixed with #5177.

**Comment by asl** [comment]
I just realized that exename is horrible broken. In few places `exename` is called without any arguments. Then it could result in some bogus exename determination. What is terrible is that it caches the result. So any subsequence calls of `exename(argv[0])` produces same bogus result (!).

Now let's take a look into `crash.cpp`. This unwanted side effect is always there as `exename()` is called in the early beginning when we initialize crash logger.

How it could be wrong without `argv[0]`? Well, one of the case is:
```c++
    } else if (getenv("_")) {
        strncpy(buffer, getenv("_"), sizeof(buffer));
        buffer[sizeof(buffer) - 1] = 0;
    } else {
```
This means if we'd execute `p4c` via some wrapper script, then it will place the full path of that wrapper script there and not `p4c` itself(!)

**Comment by fruffy** [comment]
> I just realized that `exename` is horrible broken. In few places `exename` is called without any arguments. Then it could result in some bogus exename determination. What is terrible is that it caches the result. So any subsequence calls of `exename(argv[0])` produces same bogus result (!).
> 
> Now let's take a look into `crash.cpp`. This unwanted side effect is always there as `exename()` is called in the early beginning when we initialize crash logger.
> 
> How it could be wrong without `argv[0]`? Well, one of the case is:
> 
> ```c++
>     } else if (getenv("_")) {
>         strncpy(buffer, getenv("_"), sizeof(buffer));
>         buffer[sizeof(buffer) - 1] = 0;
>     } else {
> ```
> 
> This means if we'd execute `p4c` via some wrapper script, then it will place the full path of that wrapper script there and not `p4c` itself(!)
> 
> This is exactly what was in described in #3812
> 
> And the problem is that include paths could be silently dependent on the enclosing shell, etc.

The new version should address most of these. I believe the `getenv("_")` use case is intentional but should only be triggered in special cases. It's tricky to write tests for this...

**Comment by asl** [comment]
> I believe the `getenv("_")` use case is intentional but should only be triggered in special cases.

I'd remove it. Together with caching it could produce wrong results. Caching should be removed as well, this way we always stuck to incorrect answer if it happen to appear first.

**Comment by fruffy** [comment]
> > I believe the `getenv("_")` use case is intentional but should only be triggered in special cases.
> 
> I'd remove it. Together with caching it could produce wrong results. Caching should be removed as well, this way we always stuck to incorrect answer if it happen to appear first.

Some context: https://github.com/p4lang/p4c/pull/5185#discussion_r2003776754

At least cashing was removed in the new implementation? Unless you see caching somewhere else.

File: lib/exename.cpp (hunk 1 above)
Comment (asl) [reply lib/exename.cpp:64]: Use of `_` leads to issues that are very hard to reproduce / debug:
 - There are other shells besides `bash`
 - p4c could be invoked from some wrapper script and / or app. In such case `_` might or might not be present depending on how environment is sanitized. Even worse, it may contain path to wrapper, not to `p4c` itself

I spent quite some time trying to debug wrong include paths that only manifested under test suite run and were not reproducible when the exactly same command was run manually from the shell...

**Comment by asl** [comment]
I used to see problems with "old" version. Yes, indeed caching was removed which is good.

File: lib/exename.cpp [hunk 13]
```diff
@@ -16,58 +16,82 @@ limitations under the License.
...
+    std::array<char, PATH_MAX> buffer{};
+    // TODO: Do we need to support this?
+    DWORD size = GetModuleFileNameA(nullptr, buffer.data(), static_cast<DWORD>(buffer.size()));
+    if (size > 0 && size < buffer.size()) {
+        return buffer.data();
+    } else
+#endif
+    if (auto *path = getenv("_")) {
+        return path;
+    }
```
Comment (vlstill) [inline lib/exename.cpp:73]: I am siding with @asl that this should not be used as it is a `bash` specific. And by a quick testing, even in bash it does not work always:

- When I `exec` the binary instead of running it, `getenv("_")` is name of the wrapper that `exec`-ed it. But this only works if there are no other commands executed in the script.
- Otherwise, or if I `exec` a binary from sourced script (or from interactive) I actually get `SIGSEG` when calling `getenv("_")` (probably it tries to touch the `$_` variable set by the bash that was just replaced by the `exec`-ed binary.

Comment (asl) [reply lib/exename.cpp:73]: @vlstill Thanks for the breakdown! Yes, these are exactly the cases I seen and spent quite some time debugging :)

**Comment by ChrisDodd** [comment]
> > I believe the `getenv("_")` use case is intentional but should only be triggered in special cases.
> 
> I'd remove it. Together with caching it could produce wrong results. Caching should be removed as well, this way we always stuck to incorrect answer if it happen to appear first.

If *nothing* else works, it is better than nothing, but I agree it should not be cached -- only a result that is definitively correct (eg, comes from /proc filesystem or syscall) should be cached.

File: lib/alloc_trace.cpp [hunk 14]
```diff
@@ -74,8 +74,11 @@ std::ostream &operator<<(std::ostream &out, const AllocTrace &at) {
     }
     std::sort(sorted.begin(), sorted.end(), [](auto &a, auto &b) { return a.first > b.first; });
 #if HAVE_LIBBACKTRACE
-    if (!global_backtrace_state)
-        global_backtrace_state = backtrace_create_state(exename(), 1, bt_error, &out);
+    if (!global_backtrace_state) {
+        // TODO: Do not use cstring here?
+        global_backtrace_state =
+            backtrace_create_state(cstring(getExecutablePath().c_str()).c_str(), 1, bt_error, &out);
```
[the remark this answers is not in the document]
Comment (fruffy) [reply lib/alloc_trace.cpp:80]: Creating a cstring caches the string and then returns a pointer to the cached string. There is probably a more elegant way to accomplish this.

File: lib/exename.cpp [hunk 15]
```diff
@@ -16,58 +16,82 @@ limitations under the License.
...
+#include <array>
+#include <cstring>
+#include <filesystem>
 
 namespace P4 {
 
-template <size_t N>
-static void convertToAbsPath(const char *const relPath, char (&output)[N]) {
-    output[0] = '\0';  // Default to the empty string, indicating failure.
+#if defined(__linux__) || defined(__APPLE__) || defined(__FreeBSD__) || defined(__NetBSD__)
```
[the remark this answers is not in the document]
Comment (fruffy) [reply lib/exename.cpp:25]: What would be the header file to check here? Or are you referring to the MacOS/Windows cases?

[the remark this answers is not in the document]
Comment (vlstill) [reply lib/exename.cpp:25]: This one guards `#include <unistd.h>` so I was thinking about that one. But maybe it is better to fail on system we have not foreseen this working on.

File: lib/exename.h [hunk 16]
```diff
@@ -16,10 +16,17 @@ limitations under the License.
...
 #define LIB_EXENAME_H_
 
+#include <filesystem>
+
 namespace P4 {
 
-/** Attempt to determine the executable name and return a static path to it.  Will use
- * argv0 if provided and nothing better can be found */
+/// Return the full path to the binary being executed.
+/// @returns std::nullopt if unable to determine the path.
```
[the remark this answers is not in the document]
Comment (fruffy) [reply lib/exename.h:24]: I'll keep it an empty path for now, maybe std::expected soon?

File: lib/exename.cpp (hunk 13 above)
Comment (fruffy) [reply lib/exename.cpp:73]: I removed this case.

File: lib/exename.h [hunk 17]
```diff
@@ -16,10 +16,17 @@ limitations under the License.
...
+std::filesystem::path getExecutablePath(const std::filesystem::path &suggestedPath = "");
```
[the remark this answers is not in the document]
Comment (fruffy) [reply lib/exename.h:25]: So you want two functions or require always a suggested path?

[the remark this answers is not in the document]
Comment (vlstill) [reply lib/exename.h:26]: I suggest to have two overloads.

```cpp
std::filesystem::path getExecutablePath(const std::filesystem::path &suggestedPath);
std::filesystem::path getExecutablePath();
```

The reason is that it is not obvious what the empty value for suggested path means (I'd say it is not natural "none" value of paths as it is not even a valid path).

File: lib/exename.cpp [hunk 18]
```diff
@@ -16,58 +16,84 @@ limitations under the License.
...
+        "/proc/self/path/a.out",  // Solaris
+    };
 
-    char cwd[PATH_MAX];
-    if (!getcwd(cwd, sizeof(cwd))) return;
-    const size_t cwdLen = strlen(cwd);
-    if (cwdLen == 0) return;
-    const char *separator = cwd[cwdLen - 1] == '/' ? "" : "/";
+    for (const auto &path : paths) {
+        // std::filesystem::canonical will throw on error if the path is invalid.
```
Comment (vlstill) [inline lib/exename.cpp:63]:
```suggestion
        // std::filesystem::canonical will fail if the path is invalid.

File: lib/exename.cpp [hunk 19]
```diff
@@ -16,58 +16,84 @@ limitations under the License.
...
+        // It will also try to resolve symlinks.
+        std::error_code errorCode;
+        auto canonicalPath = std::filesystem::canonical(path, errorCode);
+        // Return the path if no error was thrown.
```
Comment (vlstill) [inline lib/exename.cpp:67]:
```suggestion
        // Return the path if no error occurred.

File: lib/exename.h [hunk 20]
```diff
@@ -16,10 +16,23 @@ limitations under the License.
...
 #define LIB_EXENAME_H_
 
+#include <filesystem>
+
 namespace P4 {
 
-/** Attempt to determine the executable name and return a static path to it.  Will use
- * argv0 if provided and nothing better can be found */
+/// Return the full path to the binary being executed.
+/// @returns an empty path if unable to determine the path.
```
Comment (vlstill) [inline lib/exename.h:24]:
```suggestion
/// @returns @p suggestedPath if unable to determine the path.

**Review by vlstill — APPROVED** [review]
