### PR TITLE
Fix compile-time concatenation with negative right operand

### LINKED ISSUE #5231: Compile-time concatenation of negative constants is wrong
[const-int-concat.p4.txt](https://github.com/user-attachments/files/19706131/const-int-concat.p4.txt)

For some reason, it appears the MSB of the second parameter to `++` is cleared when it is a negative signed integer.

```p4
# got
7s0b_1100111 ++ 9s0b_111100011 ~> -7s0b_001_1001 ++ -9s0b_0_0001_1101 ~> -16s0b0011_0010_0001_1101
# expected
7s0b_1100111 ++ 9s0b_111100011 ~> -7s0b_001_1001 ++ -9s0b_0_0001_1101 ~> -16s0b0011_0000_0001_1101
```

```
729: Error compiling
729: issue5231-const-int-concat.p4(15): [--Wwarn=overflow] warning: 7s0b1100111: signed value does not fit in 7 bits
729:     const int<7> a = 7s0b_110_0111
729:                      ^^^^^^^^^^^^^
729: issue5231-const-int-concat.p4(16): [--Wwarn=overflow] warning: 9s0b111100011: signed value does not fit in 9 bits
729:     const int<9> b = 9s0b_1_1110_0011
729:                      ^^^^^^^^^^^^^^^^
729: issue5231-const-int-concat.p4(18): [--Wwarn=overflow] warning: 7s0b1100111: signed value does not fit in 7 bits
729:     const int<16> d = 7s0b_1100111
729:                       ^^^^^^^^^^^^
729: issue5231-const-int-concat.p4(18): [--Wwarn=overflow] warning: 9s0b111100011: signed value does not fit in 9 bits
729:     const int<16> d = 7s0b_1100111 ++ 9s0b_111100011
729:                                       ^^^^^^^^^^^^^^
729: issue5231-const-int-concat.p4(19): [--Wwarn=overflow] warning: 16s0b1100111111100011: signed value does not fit in 16 bits
729:     const int<16> e = 16s0b_110_0111_1_1110_0011
729:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
729: issue5231-const-int-concat.p4(22): [--Werror=expected] error: static_assert(false): static_assert failed
729:     static_assert(c == e);
729:     ^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by vlstill**
Fixes #5231. The problem is most likely in the binary representation of the `big_int` for negative numbers. The solution is to always convert the right operand to a unsigned value with the same representation as does the signed value have.

### CODE REVIEW

File: frontends/common/constantFolding.cpp [hunk 1]
```diff
@@ -798,10 +798,18 @@ const IR::Node *DoConstantFolding::postorder(IR::Concat *e) {
         return e;
     }
 
+    // The concatenation result would be wrong if the negative value was used for the second
+    // argument (because the big_int binary representation does not match what the P4 spec expects).
+    // Thereore, we convert the second argument to a unsigned literal with the same binary
```
Comment (jafingerhut) [inline frontends/common/constantFolding.cpp:803]: typo: Thereore

File: frontends/common/constantFolding.cpp [hunk 2]
```diff
@@ -798,10 +798,18 @@ const IR::Node *DoConstantFolding::postorder(IR::Concat *e) {
...
     }
 
+    // The concatenation result would be wrong if the negative value was used for the second
+    // argument (because the big_int binary representation does not match what the P4 spec expects).
+    // Therefore, we convert the second argument to a unsigned literal with the same binary
+    // representation as the P4 mandates for the signed value and concatenate these.
+    if (rt->isSigned) {
+        rt = IR::Type_Bits::get(rt->size);
+        right = new IR::Constant(rt, right->value, 10, true /* no warning */);
+    }
```
Comment (ChrisDodd) [inline frontends/common/constantFolding.cpp:808]: There's no need to create a new IR::Constant here that you're going to throw away -- just take the big_int value and fix it if it is negative:

    big_int rvalue = right->value;
    if (rvalue < 0)
        rvalue &= Util::mask(rt->size);

and then use `rvalue` later instead of `right->value`

Comment (vlstill) [reply frontends/common/constantFolding.cpp:810]: I do not like the idea of spreading a conversion function from 2-complement signed to 2-complement unsigned over multiple places in the codebase. It is already in the `Constant::handleOverflow` (invoked from the ctor) and it is not really possible to extract it from there because of the warnings which use the constant value in the logs.

I've changed the code to avoid the unnecessary dynamic allocation at least.

Comment (ChrisDodd) [reply frontends/common/constantFolding.cpp:810]: IMO this is more obscure than just doing the mask with the `big_int` value.  boost::mulitprecision specifies that bitwise operations on negative value happen as-if the values are 2s complement (regardless of what the actual underlying representation is), so that does what we want for concatenation according to the P4 spec.

**Review by ChrisDodd — APPROVED** [review]
