### PR TITLE
frontend: Fix SpecializeGenericTypes

### LINKED ISSUE #4835: Compiler Bug: `Could not find type of <Type_Header> ...` on specialized generic struct type
The following program, `bug-generic.p4` fails to typecheck when given a command `$ p4c --target bmv2 --arch v1model bug-generic.p4`.

```p4
#include <core.p4>
#include <v1model.p4>

typedef standard_metadata_t std_meta_t;

header standard_t<T> {
  T src;
  T dst;
}

struct headers_t<T> {
  standard_t<T> standard;
}

struct meta_t { }

parser MyParser(packet_in pkt, out headers_t<bit<8>> hdr, inout meta_t meta, inout std_meta_t std_meta) {
    state start {
        pkt.extract<standard_t<bit<8>>>(hdr.standard);
        // pkt.extract(hdr.standard); <-- this also fails
        transition accept;
    }
}

control MyVerifyChecksum(inout headers_t<bit<8>> hdr, inout meta_t meta) {
    apply { }
}
control MyComputeChecksum(inout headers_t<bit<8>> hdr, inout meta_t meta) {
    apply { }
}
control MyIngress(inout headers_t<bit<8>> hdr, inout meta_t meta, inout std_meta_t std_meta) {
   apply { }
}
control MyEgress(inout headers_t<bit<8>> hdr, inout meta_t meta, inout std_meta_t std_meta) {
    apply { }
}
control MyDeparser(packet_out pkt, in headers_t<bit<8>> hdr) {
    apply { }
}
V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```

Here, I defined a generic struct `headers_t<T>` that has a field of generic header type `standard_t<T>`. In the parameter of `MyParser`, the type is specialized as `headers_t<big<8>>`. So I expect that both `pkt.extract(hdr.standard);` or `pkt.extract<standard_t<bit<8>>>(hdr.standard);` should typecheck.

However, the compiler fails to typecheck with an error message:
```terminal
Compiler Bug: bug-generic.p4(19): Could not find type of <Type_Header>(40455) standard_t_0/66 header standard_t_0 {
  bit<8> src;
  bit<8> dst; }
header standard_t<T> {
       ^^^^^^^^^^
```
The same error message occurs when I do _not_ pass the type argument `standard_t<bit<8>>` to `pkt.extract` method.

### PR DESCRIPTION
**Pull request by vlstill**
A significant rewrite of `SpecializeGenericTypes`. Namely it fixes problems occurring in more complex specializations where a specialized type might depend on another specialized type and their order of insertion can be incorrect. Instead the types are now inspected to check for their dependencies and inserted just after all of the dependencies. I've also change the naming scheme of the specializations so that simple once are more readable (although for complex once the types quickly becomes ugly).

A caveat is that many passes seem to use very similar, but slightly different patterns and these passes still contain bugs (e.g. `EliminateTuples`. `SpecializeGenericFunctions`). Ideally, we would want to factor out the common parts and implement only the specific once, but I don't have time for  that (at least not now). Namely at least the insertion part should be factorable for any pass that inserts global objects that can have dependencies.

Without the changes, the added [test](https://github.com/p4lang/p4c/pull/5133/files#diff-44e02e10ea08d83ac057aa9cb153352a54085f43625481bb237b8fa27fa3c736) fails with

```
1217: Error compiling
1217: In file: ./p4c/frontends/p4/typeChecking/typeChecker.cpp:144
1217: type-spec-nested.p4(3): Could not find type of <Type_Struct>(3478) S2_0/2 struct S2_0 {
1217:   int<6> x;
1217:   int<6> y; }
1217: struct S2<T> {
1217:        ^^
```

The reason is that the specialization of `S2` is inserted *after* specialization of `S1` which refers to it.

fixes #4835

### CODE REVIEW

**Comment by vlstill** [comment]
@fruffy or anyone familiar with Bazel, any idea what is behind the bazel failure (e.g. [here](https://github.com/p4lang/p4c/actions/runs/13460549670/job/37614577989))? I can see it did not find `absl/strings/str_replace.h`, but I don't know how to find it as there is no `@com_google_absl//absl/strings:str_replace`.

File: frontends/p4/specializeGenericTypes.cpp [hunk 1]
```diff
@@ -16,51 +16,69 @@ limitations under the License.
 
 #include "specializeGenericTypes.h"
 
+#include <absl/strings/str_replace.h>
```
Comment (asl) [inline frontends/p4/specializeGenericTypes.cpp:19]: unfortunately, abseil should be included using `"`:
```suggestion
#include "absl/strings/str_replace.h"
```

Comment (vlstill) [reply frontends/p4/specializeGenericTypes.cpp]: hmm, unfortunate. Is there a way to coerce e.g. clang-format to enforce this?

Comment (asl) [reply frontends/p4/specializeGenericTypes.cpp]: Not sure. And absei's checks in `clang-tidy` does not include this as well: https://clang.llvm.org/extra/clang-tidy/checks/list.html

Comment (asl) [reply frontends/p4/specializeGenericTypes.cpp]: And for the sake of completeness, my understanding of bazel shows that `str_replace` should be in top-level `strings` library: https://github.com/abseil/abseil-cpp/blob/master/absl/strings/BUILD.bazel#L50 (`@com_google_absl//absl/strings`)

File: frontends/p4/specializeGenericTypes.h [hunk 2]
```diff
@@ -48,52 +54,65 @@ struct TypeSpecialization : public IHasDbPrint {
...
     }
     void dbprint(std::ostream &out) const override {
         out << "Specializing:" << dbp(specialized) << " from " << dbp(declaration) << " as "
-            << dbp(replacement) << " inserted at " << dbp(insertion);
+            << dbp(replacement) << " inserted at ";
+        format_container(out, insertion, '(', ')');
+    }
+};
+
+/// @brief A signature of a *concerte* specialization. None of the parameters can be type variables
```
Comment (asl) [inline frontends/p4/specializeGenericTypes.h:66]:
```suggestion
/// @brief A signature of a *concrete* specialization. None of the parameters can be type variables
```

**Review by asl — COMMENTED** [review]
Overall, looks good to me. See some minor notes and questions.

File: frontends/p4/specializeGenericTypes.cpp [hunk 3]
```diff
@@ -189,4 +204,38 @@ const IR::Node *ReplaceTypeUses::postorder(IR::StructExpression *expression) {
...
+    std::stringstream ss;
+    ss << baseType;
+    for (const auto &t : arguments) {
+        ss << "_"
+           << absl::StrReplaceAll(t, {{"<", ""}, {">", ""}, {" ", ""}, {",", "_"}, {".", "_"}});
+    }
+    return ss.str();
+}
+
+std::string to_string(const SpecSignature &sig) {
```
[the remark this answers is not in the document]
Comment (vlstill) [reply frontends/p4/specializeGenericTypes.cpp:217]: The idea was to be ADL-compatible with `std::to_string`, but yes, we sadly use `toString` in many cases, so it might be better to use that.

File: frontends/p4/specializeGenericTypes.h [hunk 4]
```diff
@@ -48,52 +54,65 @@ struct TypeSpecialization : public IHasDbPrint {
...
+/// or generic types, therefore the specialization can always be identified globally the the names
+/// of types.
+struct SpecSignature {
+    cstring baseType;
+    safe_vector<cstring> arguments;
+
+    /// @brief Get a candidate name for the instantiation.
+    std::string name() const;
+
+    bool operator<(const SpecSignature &other) const {
```
[the remark this answers is not in the document]
Comment (vlstill) [reply frontends/p4/specializeGenericTypes.h:76]: Nothing depends on the order, except that it has to be a total order for the sake of `std::map`. The insertion order is always driven by the "dependencies" that have to be defined first, and only when they are met for multiple elements then the order of the `TypeSpecializationMap::map` decides -- and even then I've left this to be `ordered_map` to make the order invariant on renaming of types. There is probably a better way to do this, but maybe that can be investigated in #5139.

File: frontends/p4/specializeGenericTypes.cpp [hunk 5]
```diff
@@ -113,49 +132,45 @@ void FindTypeSpecializations::postorder(const IR::Type_Specialized *type) {
...
 
 ///////////////////////////////////////////////////////////////////////////////////////
 
-const IR::Node *CreateSpecializedTypes::postorder(IR::Type_Declaration *type) {
-    for (auto it : specMap->map) {
-        if (it.second->declaration->name == type->name) {
-            auto specialized = it.first;
+void CreateSpecializedTypes::postorder(IR::Type_Declaration *type) {
+    for (auto &[specialized, specialization] : specMap->map) {
+        if (specialization.declaration->name == type->name) {
```
[the remark this answers is not in the document]
Comment (vlstill) [reply frontends/p4/specializeGenericTypes.cpp:142]: In the end I've realized I can use `lower_bound` on the map to find the starting point and not iterate over the entire map, so that also eliminates the extra nesting level :-).

File: frontends/p4/specializeGenericTypes.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (asl) [reply frontends/p4/specializeGenericTypes.h:84]: Yeah. My point is that with `cstring:operator<` we order everything lexicographically. But maybe we do not need to perform that amount of string comparisons.

**Comment by asl** [comment]
@vlstill Looks like generic-struct.p4 is failing

File: frontends/p4/specializeGenericTypes.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (vlstill) [reply frontends/p4/specializeGenericTypes.h:84]: Hmm, OK, I didn't see what you mean before. It would be nice to have something like `ordered_map` but with hash map for the lookup part. I can use pointer comparison for `baseType` instead as the `P4::cstring` is uniqued, but I will leave lex comparison for `arguments` as there will be much less of them and rewriting that to pointer comparison would make the code less readable.

**Comment by vlstill** [comment]
> @vlstill Looks like generic-struct.p4 is failing

Yep, there was still some dependency on processing order, it should now be fixed hopefully.

File: frontends/p4/specializeGenericTypes.h (hunk 4 above)
[the remark this answers is not in the document]
Comment (asl) [reply frontends/p4/specializeGenericTypes.h:84]: > Hmm, OK, I didn't see what you mean before. It would be nice to have something like `ordered_map` but with hash map for the lookup part.

So far it is only `string_map` that does this for `cstring` keys.

File: testdata/p4_16_samples_outputs/generic-struct-i4835.p4 [hunk 6]
```diff
@@ -0,0 +1,50 @@
+#include <core.p4>
```
Comment (fruffy) [inline testdata/p4_16_samples_outputs/generic-struct-i4835.p4:1]: Somewhat of a nonstandard issue name for the file? Although we do not really have a consistent naming scheme.

**Review by fruffy — COMMENTED** [review]
Not very familiar with that pass so it might take me a bit to give a proper review. Other might be better qualified for that.

**Review by asl — APPROVED** [review]
Great, thanks!

File: testdata/p4_16_samples_outputs/generic-struct-i4835.p4 (hunk 6 above)
Comment (vlstill) [reply testdata/p4_16_samples_outputs/generic-struct-i4835.p4]: oh, sometimes I forget which conventions differ between projects, renamed to be more consistent :-)
