### PR TITLE
[#5211] Run `UniqueNames` before `SimplifyParsers` pass

### LINKED ISSUE #5211: `SimplifyParsers` pass creates merged states with duplicate declarations
Building the following P4 program:
```
#include <core.p4>

header h_t {
    bit<16> f1;
    bit<8> f2;
}

struct Headers_t {
    h_t h;
}

parser p(packet_in p, out Headers_t headers) {
    state start { transition s0; }
    state s0 {
        bit<16> local = p.lookahead<bit<16>>();
        headers.h.f1 = local;
        transition s1;
    }
    state s1 {
        bit<8> local = p.lookahead<bit<8>>();
        headers.h.f2 = local;
        transition s2;
    }
    state s2 { transition accept; }
}

parser simple(packet_in packet, out Headers_t headers);
package top(simple e);
top(p()) main;
```
results in:
```
program.p4(12): [--Wwarn=shadow] warning: 'p' shadows 'parser p'
parser p(packet_in p, out Headers_t headers) {
                   ^
program.p4(12)
parser p(packet_in p, out Headers_t headers) {
       ^
program.p4(20): [--Werror=duplicate] error: local: Duplicates declaration local
        bit<8> local = p.lookahead<bit<8>>();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
program.p4(15)
        bit<16> local = p.lookahead<bit<16>>();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Note the following IR after the `SimplifyParsers` pass:
```
parser p(packet_in p, out Headers_t headers) {
    state start {
        bit<16> local = p.lookahead<bit<16>>();
        headers.h.f1 = local;
        bit<8> local = p.lookahead<bit<8>>();
        headers.h.f2 = local;
        transition accept;
    }
}
```

### PR DESCRIPTION
**Pull request by kfcripps**
Fixes #5211 by renaming all state-local variables with equal names before merging states in `SimplifyParsers`

### CODE REVIEW

**Review by fruffy — APPROVED** [review]

File: frontends/p4/frontend.cpp [hunk 1]
```diff
@@ -211,9 +211,12 @@ const IR::P4Program *FrontEnd::run(const CompilerOptions &options, const IR::P4P
         new SwitchAddDefault,
         new FrontEndDump(),  // used for testing the program at this point
         new RemoveAllUnusedDeclarations(*policy, true),
+        // Give each local declaration a unique internal name.
```
Comment (fruffy) [inline frontends/p4/frontend.cpp:214]: Maybe SimplifyParsers should run that pass to be safe? Or we should add a note to that pass.

**Review by ChrisDodd — APPROVED** [review]

File: frontends/p4/frontend.cpp (hunk 1 above)
Comment (kfcripps) [reply frontends/p4/frontend.cpp:214]: I did not move it to `SimplifyParsers`, because other passes that are run here at the top-level also depend on that pass running first. Or do you mean running it before `SimplifyParsers` _in addition_ to running it before `MoveDeclarations`?

Either way, I will add a note inside of `SimplifyParsers` for now.
