### PR TITLE
Fix emit inside if-statement in deparser

### LINKED ISSUE #5026: eBPF backend doesn't generate emit in if statement correctly
In the eBPF backend, if the user attempts to write an emit inside an if statement in the deparser's apply block, the generated code is semantically different from the original.  For example the following snippet:

```
control IngressDeparserImpl(packet_out packet,
                            out empty_t clone_i2e_meta,
                            out empty_t resubmit_meta,
                            out empty_t normal_meta,
                            inout headers hdr,
                            in metadata meta,
                            in psa_ingress_output_metadata_t istd)
{
    apply {
        if (meta.mymd == 0) {
            packet.emit(hdr.ethernet);
        }


        packet.emit(hdr.ipv4);
    }   
}
```

Will generate and empty if statement:

```
if (meta->mymd == 0) { 
;            }
```

and completely ignore the emit for the ethernet header

Below is the link to a tarball which has both the P4 program used to reproduce the issue and the generated C eBPF file that will illustrate the bug:
[emit-bug.tar.gz](https://github.com/user-attachments/files/17853584/emit-bug.tar.gz)

The command used to compile was:

`./p4c-ebpf --arch psa emit-bug.p4 -o emit-bug.c`

I compiled p4c with commit [8273608](https://github.com/p4lang/p4c/commit/827360828ab97301406ba279f386838acefd8943)

### PR DESCRIPTION
**Pull request by atta-ullah01**
Fixes #5026

`DeparserPrepareBufferTranslator::preorder(BlockStatement)` previously skipped `IfStatement` nodes entirely. Any `packet.emit()` wrapped in an if-block was silently ignored during both buffer sizing and header emission, resulting in empty C if-blocks.

### Changes

eBPF Backend
* `BlockStatement` traversal: Updated the visitor to traverse `IfStatement` children so nested `emit()` calls are recognized.
* If-Statement translation: Added overrides in the prepare and emit translators. This ensures we calculate the worst-case buffer size by visiting both branches and generate the proper C `if/else` syntax.
* Scope safety: Added a `hasEmitInBlock()` guard. This prevents dumping non-emit statements (like digest assignments or resubmits) into the emit scope where those variables do not exist.

TC/P4TC Backend
* Inheritance fix: The new eBPF logic leaked into `DeparserHdrEmitTranslatorPNA` and `SizeScanner`, dropping trailing semicolons in the output. Added explicit `BlockStatement` overrides to these classes to restore their original `MethodCallStatement`-only traversal.
* Statement termination: Added a `MethodCallStatement` override in PNA to delegate to `CodeGenInspector::preorder()`. This explicitly preserves the `endOfStatement()` behavior required for valid C formatting.

### Tests
* PTF validation: Added `conditional-emit.p4` and `EmitInIfStatementTest`. This verifies the generated code correctly drops or emits headers based on the condition.

### CODE REVIEW

**Comment by atta-ullah01** [comment]
A couple of things I'd appreciate feedback on:
1. I kept this scoped to `IfStatement` only. `SwitchStatement` has the same latent issue in the filter, but would also need its own preorder handlers to be correct. Worth adding in a follow-up, or should I extend this PR?
2. I didn't add a test file in this PR. Happy to add one if that's preferred — I have a PSA test ready that covers simple if, if-else, and nested if patterns. Let me know!

**Comment by jafingerhut** [comment]
A test case, especially one that fails without your changes, and passes with your changes, would be good to have.

File: backends/ebpf/ebpfDeparser.cpp [hunk 1]
```diff
@@ -47,14 +47,23 @@ DeparserPrepareBufferTranslator::DeparserPrepareBufferTranslator(const EBPFDepar
...
 }
 
+bool DeparserPrepareBufferTranslator::preorder(const IR::IfStatement *ifstmt) {
+    // Visit both branches unconditionally to size the buffer for the worst case.
+    visit(ifstmt->ifTrue);
+    if (ifstmt->ifFalse != nullptr) {
+        visit(ifstmt->ifFalse);
+    }
+    return false;
+}
```
Comment (ChrisDodd) [inline backends/ebpf/ebpfDeparser.cpp:145]: This is unnecessary -- it is identical to what the default visitor for if statements will do if you don't provide one.

File: backends/ebpf/ebpfDeparser.cpp [hunk 2]
```diff
@@ -106,6 +115,10 @@ DeparserHdrEmitTranslator::DeparserHdrEmitTranslator(const EBPFDeparser *deparse
     setName("DeparserHdrEmitTranslator");
 }
 
+bool DeparserHdrEmitTranslator::preorder(const IR::IfStatement *ifstmt) {
+    return ControlBodyTranslator::preorder(ifstmt);
+}
```
Comment (ChrisDodd) [inline backends/ebpf/ebpfDeparser.cpp:237]: Since `DeparserHdrEmitTranslator` inherits from `ControlBodyTranslator`, this also does nothing different than the default.

File: backends/ebpf/ebpfDeparser.cpp (hunk 1 above)
Comment (atta-ullah01) [reply backends/ebpf/ebpfDeparser.cpp:145]: I've rewritten this, now it uses a hasEmitInBlock() check to skip non-emit if-statements entirely. Without this guard, the default visitor generates code for assignments (like resubmit_meta.dst_addr = ... in resubmit.p4) in the buffer sizing scope where those variables aren't declared.

**Comment by atta-ullah01** [comment]
> While this generates _something_ for an emit in an if, rather than just skipping it, I'm not certain it generates the correct something. It needs a test case, preferably one that includes a ptf test covering both true and false condition cases.

Added a PTF test (EmitInIfStatementTest) with conditional-emit.p4 that uses
`if (hdr.ipv4.isValid()) { packet.emit(hdr.ipv4); }` in the deparser. The test sends an IP packet and verifies it passes through correctly.

Note: I kept the test to if-true-only instead of if-else because the buffer sizing pass sums both branches instead of taking max, which causes packet corruption when the branches have different emit sizes. I can file a separate issue for that if you want.

File: backends/ebpf/ebpfDeparser.cpp (hunk 1 above)
Comment (ChrisDodd) [reply backends/ebpf/ebpfDeparser.cpp:145]: The easier way would be to add 

    DeparserPrepareBufferTranslator::preorder(const IR::AssignmentStatement *) { return false; }

that does nothing to skip the assignments.  Then you would not need this or the EmitFinder you added.  Probably can remove the `preorder(const IR::BlockStatement *)` as well.

**Comment by atta-ullah01** [comment]
The test-p4tc-ubuntu job is currently failing for the tests under p4tc_samples_stf/. The failures appear to originate from the TC backend (p4c-pna-p4tc). I would appreciate any guidance.

File: backends/ebpf/ebpfDeparser.cpp (hunk 1 above)
Comment (atta-ullah01) [reply backends/ebpf/ebpfDeparser.cpp:145]: yeah, that's much cleaner. I'll add the `preorder(AssignmentStatement)` to skip assignments and remove the `EmitFinder`. I'll keep the `preorder(IfStatement)` on `DeparserHdrEmitTranslator` since it needs to generate the C if/else with proper braces around the emit code, but the `DeparserPrepareBufferTranslator` one can use the default visitor. Will push an update.

**Comment by vbnogueira** [comment]
> The test-p4tc-ubuntu job is currently failing for the tests under p4tc_samples_stf/. The failures appear to originate from the TC backend (p4c-pna-p4tc). I would appreciate any guidance.

It seems like you are pushing code that changes the generated files for the test cases.
When you do that you should also commit the new generated files

File: backends/ebpf/tests/p4testdata/conditional-emit.p4 [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+                           out empty_t clone_e2e_meta,
+                           out empty_t recirculate_meta,
+                           inout headers hdr,
+                           in metadata meta,
+                           in psa_egress_output_metadata_t istd,
+                           in psa_egress_deparser_input_metadata_t edstd)
+{
+    apply {
+        packet.emit(hdr.ethernet);
+        if (hdr.ipv4.isValid()) {
```
Comment (jafingerhut) [inline backends/ebpf/tests/p4testdata/conditional-emit.p4]: I would recommend almost _any_ condition except `hdr.ipv4.isValid()` here in the test case, because the behavior of `packet.emit(hdr.ipv4)` all by itself is identical to `if (hdr.ipv4.isValid()) packet.emit(hdr.ipv4);`, thus if your p4c changes have certain kinds of bugs, you will not be able to tell from packet tests whether the compiler output is correct or not.

For example, perhaps use instead the condition `if (hdr.ethernet.dst_mac[40:40] == 1)`.  It is straightforward in a packet test case to make that condition independent of `hdr.ipv4.isValid()`

File: backends/ebpf/ebpfDeparser.cpp (hunk 1 above)
Comment (atta-ullah01) [reply backends/ebpf/ebpfDeparser.cpp:145]: I tried adding `preorder(AssignmentStatement) { return false; }` as you suggested, that fixes the buffer sizing pass. However, the emit pass `(DeparserHdrEmitTranslator)` still needs the hasEmitInBlock guard because it generates C code for the if-condition. In l2l3-acl.p4, the deparser has if `(local_metadata.send_mac_learn_msg) { digest.pack(...); }` without the guard, the emit pass generates if `(local_metadata.send_mac_learn_msg)` which fails because `local_metadata` is not declared in the emit scope.

File: backends/ebpf/tests/p4testdata/conditional-emit.p4 (hunk 3 above)
Comment (atta-ullah01) [reply backends/ebpf/tests/p4testdata/conditional-emit.p4]: changed the condition to hdr.ethernet.dstAddr[7:0] == 1. The PTF test covers both branches: dst_mac=01 verifies IPv4 is emitted, dst_mac=02 verifies IPv4 is NOT emitted (ethernet-only output).

**Comment by atta-ullah01** [comment]
yayyy finally, all cases passed 😭
one more force push and i would've died of embarrassment

**Comment by atta-ullah01** [comment]
> > The test-p4tc-ubuntu job is currently failing for the tests under p4tc_samples_stf/. The failures appear to originate from the TC backend (p4c-pna-p4tc). I would appreciate any guidance.
> 
> It seems like you are pushing code that changes the generated files for the test cases. When you do that you should also commit the new generated files

Thanks for catching @vbnogueira! it was an inheritance leak. my new overrides accidentally bled into the TC backend.
fixed it by adding explicit overrides to the PNA classes

**Comment by fruffy** [comment]
> one more force push and i would've died of embarrassment

No worries, the eBPF and TC back ends are quite entangled. They are not easy to work with.

File: backends/ebpf/tests/ptf/test.py [hunk 4]
```diff
@@ -996,3 +996,21 @@ def runTest(self):
...
             testutils.send_packet(self, PORT0, pkt)
             testutils.verify_packet_any_port(self, exp_pkt, PTF_PORTS)
+
+
+class EmitInIfStatementTest(P4EbpfTest):
+    """Test for issue #5026: emit inside if-statement in deparser."""
+
+    p4_file_path = "p4testdata/conditional-emit.p4"
+
+    def runTest(self):
```
Comment (jafingerhut) [inline backends/ebpf/tests/ptf/test.py]: You already have these cases covered:

+ hdr.ipv4.isValid()=true, (dstAddr[7:0] == 1)=true
+ dr.ipv4.isValid()=true, (dstAddr[7:0] == 1)=false

Please add two more test cases to more fully cover your changes.

+ hdr.ipv4.isValid()=false, (dstAddr[7:0] == 1)=true
+ dr.ipv4.isValid()=false, (dstAddr[7:0] == 1)=false

**Comment by fruffy** [comment]
@vbnogueira Can you give this a review?

**Comment by atta-ullah01** [comment]
> I gave a quick test on the original reproducer [1] There are still a couple of issues :
> 
>     1. The old empty if-statement is still there
> 
> 
> ```
>  if (meta->mymd == 0) { 
> ;            }
> ```
> 
>     2. It is still incrementing `outHeaderLength`
> 
> 
> Even if the ethernet header is not emitted, the code is still incrementing `outHeaderLength` by its size:
> 
> ```
> int outHeaderLength = 0;
> if (parsed_hdr->ethernet.ebpf_valid) {
>     outHeaderLength += 112;
> }
> ...
> 
> if (meta->mymd == 0) {
>        if (parsed_hdr->ethernet.ebpf_valid) {
>            if ((u8*)ebpf_packetEnd < hdr_start + BYTES(112)) {
>                return TC_ACT_SHOT;
>            }
> ...
> ```
> 
> [1] #5026

Fixed both issues
