### PR TITLE
Fix bugs related to StructureExpressions

### LINKED ISSUE #2543: Some problems with function calls in struct initialization
I think one of the recent merges has unearthed some problems with structure initializations and function calls within them.
The following two programs throw errors that do not seem correct. 

[return_hdr_struct.p4.txt](https://github.com/p4lang/p4c/files/5217665/return_hdr_struct.p4.txt)
```
MidEnd_10_HandleNoMatch
MidEnd_11_SimplifyParsers
MidEnd_12_StrengthReduction
bugs/crash/return_hdr_struct.p4(17): [--Werror=type-error] error: AssignmentStatement: Cannot unify tuple_0 with ethernet_t
    return { { 1, 1, produce_val() }};
    ^^^^^^
bugs/crash/return_hdr_struct.p4(2)
header ethernet_t {
       ^^^^^^^^^^
```

[struct_function_call.p4.txt](https://github.com/p4lang/p4c/files/5217668/struct_function_call.p4.txt)
```
FrontEnd_47_InlineFunctions
P4::TypeChecking_0_ResolveReferences
P4::TypeChecking_1_TypeInference
SetHeaders_0_TypeChecking
In file: p4c/frontends/p4/typeMap.cpp:95
[31mCompiler Bug[0m: Could not find type for <StructExpression>(7655)
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
IndexedVector had a validation function, but it was never called. If it was, it would have caught one of these two bugs.
Fixes #2543

### CODE REVIEW

File: frontends/p4/sideEffects.cpp [hunk 1]
```diff
@@ -160,7 +160,9 @@ const IR::Node* DoSimplifyExpressions::preorder(IR::StructExpression* expression
         auto path = addAssignment(expression->srcInfo, tmp, v->expression);
         typeMap->setType(path, t);
         v = new IR::NamedExpression(v->name, path);
+        vec.push_back(v);
     }
+    expression->components = vec;
```
Comment (ChrisDodd) [inline frontends/p4/sideEffects.cpp:165]: This seems pointless?  `v` is already a reference to the pointer in expression->components.  Simpler would be to just get rid of the unused `vec`

File: frontends/p4/structInitializers.cpp [hunk 2]
```diff
@@ -89,6 +89,25 @@ const IR::Node* CreateStructInitializers::postorder(IR::AssignmentStatement* sta
...
+        return statement;
+
+    auto ftype = typeMap->getType(func);
+    BUG_CHECK(ftype->is<IR::Type_Method>(), "%1%: expected a method type for function", ftype);
+    auto mt = ftype->to<IR::Type_Method>();
+    auto returnType = mt->returnType;
+    CHECK_NULL(returnType);
+
+    auto init = convert(statement->expression, returnType);
+    if (init != statement->expression)
```
Comment (ChrisDodd) [inline frontends/p4/structInitializers.cpp:106]: pointless `if` test?  If the pointers are equal, the assignment would have no effect, so why bother?

**Review by ChrisDodd — APPROVED** [review]

File: frontends/p4/sideEffects.cpp (hunk 1 above)
Comment (mbudiu-vmw) [reply frontends/p4/sideEffects.cpp]: Actually this does not work because of issue https://github.com/p4lang/p4c/issues/43
