### PR TITLE
Fix SIGSEGV when v1model version is negative or invalid

### LINKED ISSUE #5296: `SIGSEGV` when wrong initializer is given to `__v1model_version`
```p4
 const bit<32> __v1model_version = error.pkt;
```

```p4
const bit<32> __v1model_version = {};
```

The above two programs, when given to `p4test`, results in `SIGSEGV`:

```
In file: /p4c/lib/crash.cpp:299
Compiler Bug: Exiting with SIGSEGV
```

I believe this crash is specific to the name `__v1model_version`, where

```p4
const bit<32> x = error.pkt;
```

is rejected (as expected) without SIGSEGV:

```
nocrash-299-v1model.p4(1): [--Werror=not-found] error: error: declaration not found
const bit<32> x = error.pkt;
                  ^^^^^
```

### PR DESCRIPTION
**Pull request by jhavrane**
Adds missing validation for v1model value constant. Fixes #5296

### CODE REVIEW

**Comment by jhavrane** [comment]
Also tried with value from the issue:

```
Error compiling
issue5296.p4(2): [--Werror=expected] error: error.pkt: expected v1model version to be a non-negative number
const bit<32> __v1model_version = error.pkt;
                                  ^^^^^^^^^
```

File: frontends/p4/getV1ModelVersion.h [hunk 1]
```diff
@@ -12,6 +12,10 @@ class GetV1ModelVersion : public Inspector {
     bool preorder(const IR::Declaration_Constant *dc) override {
         if (dc->name == "__v1model_version") {
             const auto *val = dc->initializer->to<IR::Constant>();
+            if (!val) {
```
Comment (ChrisDodd) [inline frontends/p4/getV1ModelVersion.h]: Probably should be `if (!val || val->value < 0)`.  The only reason this seems to work without it is because `-6419018` is initially `IR::Neg` on an `IR::Constant`, and if constant-folding runs it will be simplified.

Might also want to limit it to just known valid versions of `V1MODEL_VERSION`

Comment (jhavrane) [reply frontends/p4/getV1ModelVersion.h]: @ChrisDodd, is there any list of valid versions of `V1MODEL_VERSION` somewhere?

Comment (jhavrane) [reply frontends/p4/getV1ModelVersion.h]: Grepped this list of versions from `testdata/`
```
20160101
20180000
20180101
20200000
20200408
```

**Comment by ChrisDodd** [comment]
looks like you accidentally rebased main on to this?  Or something that make the change look much bigger than it should be.

**Comment by jhavrane** [comment]
Fixed invalid rebase. I've added some simple version check. It checks that version is between defined constants.
