### PR TITLE
test: Update install_fedora_deps.sh

### LINKED ISSUE #3189: Build is broken on fedora
I really don't know why though; seems to be in the installation of dependencies
this is the error:
`tools/install_fedora_deps.sh: line 77: ./autogen.sh: No such file or directory`

### PR DESCRIPTION
**Pull request by rst0git**
The simple_switch_grpc target has been integrated with the main `autogen.sh` and `configure.ac` files.

https://github.com/p4lang/behavioral-model/pull/1105

Fixes #3189

### CODE REVIEW

File: tools/install_fedora_deps.sh [hunk 1]
```diff
@@ -72,12 +72,6 @@ cd behavioral-model
 ./configure --with-pdfixed --with-thrift --with-pi --with-stress-tests --enable-debugger
 make
 make install-strip
-
-cd targets/simple_switch_grpc/
```
Comment (mbudiu-vmw) [inline tools/install_fedora_deps.sh:76]: this stuff is not needed?

**Review by mbudiu-vmw — APPROVED** [review]

File: tools/install_fedora_deps.sh (hunk 1 above)
Comment (rst0git) [reply tools/install_fedora_deps.sh:76]: This step is no longer necessary because the `configure.ac` file for simple_switch_grpc has been integrated with the `configure.ac` file in the top-level directory.
