### PR TITLE
Handle list literals in IR::Cast case in constantFolding.cpp

### LINKED ISSUE #401: Compiler bug in constant folding
Program:
```
#include <v1model.p4>

header h_t {
  bit<8> f;
}

struct my_packet {
  h_t h;
}

struct my_metadata {

}

parser MyParser(packet_in b, out my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  state start {
    transition accept;
  }
}

control MyVerifyChecksum(in my_packet hdr, inout my_metadata meta) {
  apply { }
}

control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply { 
    bit<1> b = (bit<1>) { 0 };
  }
}

control MyEgress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  apply { }
}

control MyComputeChecksum(inout my_packet p, inout my_metadata m) {
  apply { }
}

control MyDeparser(packet_out b, in my_packet p) {
  apply { }
}

/* Instantiate */
MyParser() p;
MyVerifyChecksum() vck;
MyIngress() i;
MyEgress() e;
MyComputeChecksum() cck;
MyDeparser() dp;

V1Switch(p, vck, i, e, cck, dp) main;
```

Error:
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../frontends/common/constantFolding.cpp:631
/home/vagrant/min.p4(27): {0};: expected a boolean literal
    bit<1> b = (bit<1>) { 0 };
                        ^^^^^

Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by jnfoster**
The IR::Cast case had a bug where it assumed that a constant was either a boolean or numeric literal. This pull request adds an extra case to handle list literals.

Fixes #401.

### CODE REVIEW

File: frontends/common/constantFolding.cpp [hunk 1]
```diff
@@ -627,14 +627,15 @@ const IR::Node *DoConstantFolding::postorder(IR::Cast *e) {
...
-        } else {
-            BUG_CHECK(expr->is<IR::BoolLiteral>(), "%1%: expected a boolean literal", expr);
+        } else if (expr -> is<IR::BoolLiteral>()) {
             auto arg = expr->to<IR::BoolLiteral>();
             int v = arg->value ? 1 : 0;
             auto result = new IR::Constant(e->srcInfo, type, v, 10);
             setConstant(e, result);
             return result;
-        }
+	  } else {
```
Comment (mbudiu-vmw) [inline frontends/common/constantFolding.cpp]: You should set your editor to use 4 spaces.
Please add a comment indicating what else this could be, e.g., another constant, which probably the typeChecker will reject.

Comment (jnfoster) [inline frontends/common/constantFolding.cpp]: Was rushing to get this out with @sethfowler before I had to pick up my kids and hadn't even indented :-) Fixed now.

**Comment by jnfoster** [comment]
Sorry, what is an IR::ListExpression where all of the elements are constants if not a "list literal?
https://github.com/p4lang/p4c/blob/master/frontends/p4/p4-parse.ypp#L904

I'm happy to change what it's called, or replace the comment with something else entirely if you can suggest the appropriate wording. I was only trying to make it precise based on what the code actually does.

And if we were serious about coding defensively, we would have a type to represent the kinds of things that `getConstant` can return. Then the type checker could help us detect when we missed a case, as was the cause of this bug. Maybe that's overkill, but we have an existence proof that it might sometimes trip us up...
