### PR TITLE
Fix EnumeratorHandle compilation

### LINKED ISSUE #5107: Add EnumeratorHandle::operator== to avoid compilation error with Google internal toolchain
This is an issue caught by Google internal compilation tests. The suggested fix is to add

```c++
bool operator==(const EnumeratorHandle<T> &other) const;
```

right above

https://github.com/p4lang/p4c/blob/8f122d66cfdb5436dc985300f666709350e8c370/lib/enumerator.h#L63

And add its implementation

```c++
template <typename T>
bool EnumeratorHandle<T>::operator==(const EnumeratorHandle<T> &other) const {
    return !(*this != other);
}
```

in the same file.

### PR DESCRIPTION
**Pull request by qobilidop**
Fixes #5107.

### CODE REVIEW

File: lib/enumerator.h [hunk 1]
```diff
@@ -630,6 +631,11 @@ const EnumeratorHandle<T> &EnumeratorHandle<T>::operator++() {
     return *this;
 }
 
+template <typename T>
+bool EnumeratorHandle<T>::operator==(const EnumeratorHandle<T> &other) const {
+    return !(*this != other);
```
Comment (jafingerhut) [inline lib/enumerator.h:636]: Sorry for the noise comment, but is this way of defining `operator==` common in C++?

Comment (asl) [reply lib/enumerator.h:636]: Usually the opposite (`operator!=` is implemented from `operator==`), however, here we already having `operator!=` with quite peculiar semantics.

Comment (qobilidop) [reply lib/enumerator.h:636]: As @asl pointed out in https://github.com/p4lang/p4c/issues/5107#issuecomment-2608881119, it's probably better to first define `operator==` and then define `operator!=` as `!(*this == other)`, which is also the semantics specified in https://en.cppreference.com/w/cpp/named_req/InputIterator. I still don't have a good understanding here to make that further simplification. Maybe someone with a better understanding can do it in a separate PR.

Comment (ChrisDodd) [reply lib/enumerator.h:636]: > Usually the opposite (`operator!=` is implemented from `operator==`),

Indeed, with C++20, you don't even need to do that -- if you define `operator==`, the compiler will synthesize `operator!=` for you

**Review by ChrisDodd — APPROVED** [review]
