### PR TITLE
Handle correctly general switch statements when simplifying

### LINKED ISSUE #3619: Compiler bug with switch fall through at the end (and no other statements)
Take:
```
control c(in bit<4> v)
{
  apply{
    switch(v) {
      default:
    }
  }
}
```

We get a warning like we should but then a compiler bug happens:
```
testsuite/p4c.language/valid/control/bitswitch-1.p4(6): [--Wwarn=missing] warning: SwitchCase: fallthrough with no statement
      default:
      ^^^^^^^
In file: /home/apinski/src/p4/p4c/frontends/p4/simplify.cpp:99
Compiler Bug: testsuite/p4c.language/valid/control/bitswitch-1.p4(4): v;: expected a Member
    switch(v) {
           ^
```
Yes the above code should not really appear in real code, I was just writing testcases for my front-end to make sure I did not mess it up and happened upon the crash here.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>
Fixes #3619

### CODE REVIEW

**Comment by apinski-cavium** [comment]
Does this handle side effects in the switch expression that is:
```
action NoAction() {}
control c(in bit<4> v)
{
  table t { actions = {} }
  apply{
    switch(t.apply().hit) {
      default:
    }
  }
}
```
And still have the table apply there?

**Comment by mbudiu-vmw** [comment]
It should, if there is a method call in the switch statement it is preserved.
I was assuming this pass is run after the pass which moves side effects in separate statements, but I have to check.

**Comment by mbudiu-vmw** [comment]
I don't think this is conservative enough, since it is also run before the side-effect-ordering pass.
I will improve it.

File: frontends/p4/simplify.cpp [hunk 1]
```diff
@@ -92,16 +93,19 @@ const IR::Node* DoSimplifyControlFlow::postorder(IR::EmptyStatement* statement)
...
-        // switch conditions.  The parser should have rejected programs for
-        // which this is not the case.
-        BUG_CHECK(statement->expression->is<IR::Member>(),
-                  "%1%: expected a Member", statement->expression);
-        auto expr = statement->expression->to<IR::Member>();
-        BUG_CHECK(expr->expr->is<IR::MethodCallExpression>(),
-                  "%1%: expected a table invocation", expr->expr);
-        auto mce = expr->expr->to<IR::MethodCallExpression>();
-        return new IR::MethodCallStatement(mce->srcInfo, mce);
+        // If this is a table application remove the switch altogether but keep
```
Comment (fruffy) [inline frontends/p4/simplify.cpp:96]: Do we have a test for this?

**Review by fruffy — APPROVED** [review]

File: frontends/p4/simplify.cpp (hunk 1 above)
Comment (fruffy) [reply frontends/p4/simplify.cpp:96]: Also another test for a function call with side-effects could be useful.

**Review by rst0git — APPROVED** [review]
LGTM

File: frontends/p4/simplify.cpp (hunk 1 above)
Comment (mbudiu-vmw) [reply frontends/p4/simplify.cpp:96]: issue3619-1.p4 is testing the side-effect.

Comment (fruffy) [reply frontends/p4/simplify.cpp:96]: But that function call is side-effect free. Also this does not include a table.apply(), right?

Comment (mbudiu-vmw) [reply frontends/p4/simplify.cpp:96]: This pass does not know that the function has no side effects. All tests with table applications would qualify for the second case.

Comment (fruffy) [reply frontends/p4/simplify.cpp:96]:
```
if (SideEffects::check(statement->expression, this, refMap, typeMap))
    // This can happen if this pass is run before SideEffectOrdering.
    return statement;
```
I am trying to understand this segment. If the function call has side effects, ideally only the method call statement should remain, right? I do not think we have a test for this. 

Similarly, 
`if (TableApplySolver::isActionRun(statement->expression, refMap, typeMap)) {`
should check whether there is an action_run call and then only leave the table apply statement. 

I assume we have tests already for this case? Since this was the default behavior.

Comment (mbudiu-vmw) [reply frontends/p4/simplify.cpp:96]: If the argument of the switch may have side-effects then we leave it unchaged. This pass is invoked again later, after SideEffectOrdering has removed calls with side effects from switch statements (all except table.apply().action_run), and that case will never occur again.
