### PR TITLE
[#5254] Emit error message for duplicate `switch` case labels

### LINKED ISSUE #5254: Fails to reject duplicate switch labels
According to [12.7.3.](https://p4.org/p4-spec/docs/p4-16-working-draft.html#_notes_common_to_all_switch_statements) of the spec, duplicate switch labels are not allowed:
> 12.7.3. Notes common to all switch statements
> It is a compile-time error if two labels of a switch statement equal each other.

However, p4test does not print any errors for the following program:
```p4
extern bit<8> baz();
control c()() {
  apply {
    switch (baz()) {
      1: {}
      1: {}
    }
  }
}

```

### PR DESCRIPTION
**Pull request by kfcripps**
Fixes #5254

### CODE REVIEW

File: frontends/p4/typeChecking/typeCheckStmt.cpp [hunk 1]
```diff
@@ -85,6 +86,12 @@ const IR::Node *TypeInferenceBase::postorder(const IR::SwitchStatement *stat) {
                 setCompileTimeConstant(c->label);
                 changed = true;
             }
+            for (unsigned j = i + 1; j < sclone->cases.size(); j++) {
```
Comment (asl) [inline frontends/p4/typeChecking/typeCheckStmt.cpp]: do we really need to have this quadratic loop? Why not put all the cases in the map as you go. There is already some code above with `foundLabels`, right? (and we'd probably want to replace it with `string_map<const IR::Node*>` while there)

**Review by asl — CHANGES_REQUESTED** [review]

File: frontends/p4/typeChecking/typeCheckStmt.cpp (hunk 1 above)
Comment (kfcripps) [reply frontends/p4/typeChecking/typeCheckStmt.cpp]: @asl That will not work here. The a map works above because the switch labels are guaranteed to be action names. Here we need to compare arbitrary expressions, which are not necessarily the same `IR::Node*`. So `equiv()` is needed.

**Comment by ChrisDodd** [comment]
IMO a duplicate switch label is not a type error, but a different class of semantic error.  So this check should really be somewhere else, not in typeChecking.  `ValidateParsedProgram` perhaps, though that runs before ConstantFolding, so tags with different expressions that fold to the same thing would not be caught.

Doing it in TypeChecking is also inefficient as typeChecking run multiple (many) times and this should only be done once.

**Comment by kfcripps** [comment]
> IMO a duplicate switch label is not a type error, but a different class of semantic error. So this check should really be somewhere else, not in typeChecking. `ValidateParsedProgram` perhaps, though that runs before ConstantFolding, so tags with different expressions that fold to the same thing would not be caught.
> 
> Doing it in TypeChecking is also inefficient as typeChecking run multiple (many) times and this should only be done once.

Ok, I can add a new pass after `ConstantFolding` for this check.
